"""Removendo telefone

Revision ID: d3277eb82506
Revises: 5645dd6e9b31
Create Date: 2025-09-25 08:12:40.791912

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd3277eb82506'
down_revision = '5645dd6e9b31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('telefone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefone', mysql.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
